task_name: DmesonJets
run_period: LHC14j4c
mode: AOD
full_jets: false
charged_jets: true
MC: true
charm_enhanced: false
file_list: fileLists/files_LHC14j4c_AOD.txt
reco_pass: 4
cent_bins: no
cent_type: no
rdhf_cuts_dzero: "RDHFCuts/RDHFCuts_LHC10_pass4.root"
rdhf_cuts_dstar: "RDHFCuts/RDHFCuts_LHC10_pass4.root"
beam_type: pp
is_pythia: yes
ue_sub: yes
dstar: yes
dzero: yes
trigger: []
