task_name: DmesonJets
run_period: LHC15o
mode: AOD
full_jets: false
charged_jets: true
MC: false
charm_enhanced: false
file_list: fileLists/files_LHC15o_pass1_AOD.txt
reco_pass: 1
cent_bins: [0, 20, 50, 90]
cent_type: new
rdhf_cuts_dzero: "RDHFCuts/RDHFCuts_LHC15o_pass1_Cent2.root"
rdhf_cuts_dstar: "RDHFCuts/RDHFCuts_LHC15o_pass1_Cent2.root"
beam_type: PbPb
is_pythia: no
ue_sub: yes
dstar: no
dzero: yes
trigger: [kINT7]
