task_name: EMCalTriggerQA
run_period: LHC16d
mode: ESD
file_list: fileLists/files_LHC16d_emcal_trigger_252373.txt
triggers:
- 
  label: CEMC7
  accept: [CEMC7-B-NOPF-CENTNOTRD]
- 
  label: CEMC8
  accept: [CEMC8-B-NOPF-CENTNOTRD]
- 
  label: CEMC7NOCEMC7EG1
  accept: [CEMC7-B-NOPF-CENTNOTRD]
  reject: [CEMC7EG1-B-NOPF-CENTNOTRD]
- 
  label: CDMC7
  accept: [CDMC7-B-NOPF-CENTNOTRD]
- 
  label: CEMC7CDMC7
  accept: [CEMC7-B-NOPF-CENTNOTRD, CDMC7-B-NOPF-CENTNOTRD]
- 
  label: CEMC7EG1
  accept: [CEMC7EG1-B-NOPF-CENTNOTRD]
- 
  label: CEMC7EG2
  accept: [CEMC7EG2-B-NOPF-CENTNOTRD]
- 
  label: CEMC7EJ1
  accept: [CEMC7EJ1-B-NOPF-CENTNOTRD]
- 
  label: CEMC7EJ2
  accept: [CEMC7EJ2-B-NOPF-CENTNOTRD]
- 
  label: CDMC7DG1
  accept: [CDMC7DG1-B-NOPF-CENTNOTRD]
- 
  label: CDMC7DG2
  accept: [CDMC7DG2-B-NOPF-CENTNOTRD]
- 
  label: CDMC7DJ1
  accept: [CDMC7DJ1-B-NOPF-CENTNOTRD]
- 
  label: CDMC7DJ2
  accept: [CDMC7DJ2-B-NOPF-CENTNOTRD]
- 
  label: CEMC7EG1CDMC7DG1
  accept: [CEMC7EG1-B-NOPF-CENTNOTRD, CDMC7DG1-B-NOPF-CENTNOTRD]
- 
  label: CEMC7EG2CDMC7DG2
  accept: [CEMC7EG2-B-NOPF-CENTNOTRD, CDMC7DG2-B-NOPF-CENTNOTRD]
- 
  label: CEMC7EJ1CDMC7DJ1
  accept: [CEMC7EJ1-B-NOPF-CENTNOTRD, CDMC7DJ1-B-NOPF-CENTNOTRD]
- 
  label: CEMC7EJ2CDMC7DJ2
  accept: [CEMC7EJ2-B-NOPF-CENTNOTRD, CDMC7DJ2-B-NOPF-CENTNOTRD]
